apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-admin-binding
  labels:
    workflowFriendlyName: build_deploy_aks_role
    workflow: actions.github.com-k8s-deploy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
# - kind: User
#   name: ahethaysham.ahmed@mphasis.com  # Replace with the desired username or service account
- kind: ServiceAccount
  name: default # Replace with the name of your ServiceAccount
  namespace: default # Replace with the namespace where the ServiceAccount resides
