name: Deploy AKS-Construction

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy_aks:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/azure-cli
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Azure CLI
        run: |
          az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
      - name: Deploy AKS cluster
        uses: Azure/AKS-Construction@0.9.14
        with:
          resource-group: appdemogroup2
          cluster-name: xaapaks1
          agent-count: 1
          upgrade-channel: stable
          sku-tier: Paid
          max-agent-count: 20
          custom-vnet: true
          create-network-security-groups: true
          enable-aad: true
          disable-local-accounts: true
          enable-azure-rbac: true
          admin-principal-id: ${{ secrets.USER_OBJECT_ID }}
          registries-sku: Premium
          acr-push-role-principal-id: ${{ secrets.USER_OBJECT_ID }}
          omsagent: true
          retention-in-days: 30
          network-policy: azure
          azurepolicy: audit
          authorized-ip-ranges: '["10.10.0.0/24"]'
          ingress-application-gateway: true
          appgw-count: 0
          appgw-sku: WAF_v2
          appgw-max-count: 10
          appgw-kv-integration: true
          keyvault-aks-csi: true
          keyvault-create: true
          keyvault-officer-role-principal-id: ${{ secrets.USER_OBJECT_ID }}
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          USER_OBJECT_ID: ${{ secrets.USER_OBJECT_ID }}
