name: Execute Azure CLI commands 

on:
  push:
    branches: [main]

jobs:
  execute-az:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/azure-cli
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Azure
        run: az login --service-principal -u ${{ secrets.ARM_CLIENT_ID }} -p ${{ secrets.ARM_CLIENT_SECRET }} --tenant ${{ secrets.ARM_TENANT_ID }}
      - name: Execute Azure CLI commands
        shell: bash
        run: |
          # Create resource group, and an identity with contributor access that github can federate
          az group create -l WestEurope -n appdemogroup2

          # Create an Azure AD app, and retrieve its ID and Application (client) ID
          app=($(az ad app create --display-name azure-voting-app-redis --query "[appId,id]" -o tsv | tr ' ' "\n"))
          
          # Create a service principal for the app, and retrieve its object ID
          spId=$(az ad sp create --id ${app[0]} --query objectId -o tsv)

          # Retrieve the subscription ID
          subId=$(az account show --query id -o tsv)

          # Assign the "Owner" role to the service principal at the resource group scope
          az role assignment create --role owner --assignee-object-id $spId --assignee-principal-type ServicePrincipal --scope /subscriptions/$subId/resourceGroups/appdemogroup2

          # Create a new federated identity credential
          az rest --method POST --uri "https://graph.microsoft.com/beta/applications/${app[1]}/federatedIdentityCredentials" --body "{\"name\":\"azure-voting-app-redis-main-gh\",\"issuer\":\"https://token.actions.githubusercontent.com\",\"subject\":\"repo:zaracheema/azure-voting-app-redis:ref:refs/heads/main\",\"description\":\"Access to branch main\",\"audiences\":[\"api://AzureADTokenExchange\"]}"

          # Set Secrets
          gh secret set --repo https://github.com/zaracheema/azure-voting-app-redis AZURE_CLIENT_ID -b ${app[0]}
          gh secret set --repo https://github.com/zaracheema/azure-voting-app-redis AZURE_TENANT_ID -b $(az account show --query tenantId -o tsv)
          gh secret set --repo https://github.com/zaracheema/azure-voting-app-redis AZURE_SUBSCRIPTION_ID -b $subId
          gh secret set --repo https://github.com/zaracheema/azure-voting-app-redis USER_OBJECT_ID -b $spId
